/**
 * Symbol tables for the math typesetter.
 *
 * Each LaTeX command maps to a Unicode rendering and an ASCII fallback. The
 * ASCII variant is used when `mathMode === "ascii"` (terminals/fonts without
 * good Unicode coverage); it never emits non-ASCII bytes.
 */

export interface Glyph {
	/** Preferred Unicode rendering. */
	u: string;
	/** ASCII-only fallback. */
	a: string;
}

/**
 * LaTeX command (without the leading backslash) -> glyph.
 *
 * Covers Greek letters, relations, binary operators, arrows, set/logic symbols,
 * and a few named constants. Commands not present here are unsupported and cause
 * the parser to bail (so the whole expression falls back to its raw source).
 */
export const SYMBOLS: Record<string, Glyph> = {
	// Lowercase Greek
	alpha: { u: "α", a: "alpha" },
	beta: { u: "β", a: "beta" },
	gamma: { u: "γ", a: "gamma" },
	delta: { u: "δ", a: "delta" },
	epsilon: { u: "ε", a: "epsilon" },
	varepsilon: { u: "ε", a: "epsilon" },
	zeta: { u: "ζ", a: "zeta" },
	eta: { u: "η", a: "eta" },
	theta: { u: "θ", a: "theta" },
	vartheta: { u: "ϑ", a: "theta" },
	iota: { u: "ι", a: "iota" },
	kappa: { u: "κ", a: "kappa" },
	lambda: { u: "λ", a: "lambda" },
	mu: { u: "μ", a: "mu" },
	nu: { u: "ν", a: "nu" },
	xi: { u: "ξ", a: "xi" },
	pi: { u: "π", a: "pi" },
	varpi: { u: "ϖ", a: "pi" },
	rho: { u: "ρ", a: "rho" },
	varrho: { u: "ϱ", a: "rho" },
	sigma: { u: "σ", a: "sigma" },
	varsigma: { u: "ς", a: "sigma" },
	tau: { u: "τ", a: "tau" },
	upsilon: { u: "υ", a: "upsilon" },
	phi: { u: "φ", a: "phi" },
	varphi: { u: "ϕ", a: "phi" },
	chi: { u: "χ", a: "chi" },
	psi: { u: "ψ", a: "psi" },
	omega: { u: "ω", a: "omega" },
	// Uppercase Greek
	Gamma: { u: "Γ", a: "Gamma" },
	Delta: { u: "Δ", a: "Delta" },
	Theta: { u: "Θ", a: "Theta" },
	Lambda: { u: "Λ", a: "Lambda" },
	Xi: { u: "Ξ", a: "Xi" },
	Pi: { u: "Π", a: "Pi" },
	Sigma: { u: "Σ", a: "Sigma" },
	Upsilon: { u: "Υ", a: "Upsilon" },
	Phi: { u: "Φ", a: "Phi" },
	Psi: { u: "Ψ", a: "Psi" },
	Omega: { u: "Ω", a: "Omega" },
	// Relations
	leq: { u: "≤", a: "<=" },
	le: { u: "≤", a: "<=" },
	geq: { u: "≥", a: ">=" },
	ge: { u: "≥", a: ">=" },
	neq: { u: "≠", a: "!=" },
	ne: { u: "≠", a: "!=" },
	equiv: { u: "≡", a: "==" },
	approx: { u: "≈", a: "~=" },
	cong: { u: "≅", a: "~=" },
	sim: { u: "∼", a: "~" },
	simeq: { u: "≃", a: "~=" },
	propto: { u: "∝", a: "prop" },
	ll: { u: "≪", a: "<<" },
	gg: { u: "≫", a: ">>" },
	subset: { u: "⊂", a: "subset" },
	subseteq: { u: "⊆", a: "subseteq" },
	supset: { u: "⊃", a: "supset" },
	supseteq: { u: "⊇", a: "supseteq" },
	// Binary operators
	times: { u: "×", a: "x" },
	div: { u: "÷", a: "/" },
	cdot: { u: "·", a: "*" },
	ast: { u: "∗", a: "*" },
	star: { u: "⋆", a: "*" },
	pm: { u: "±", a: "+/-" },
	mp: { u: "∓", a: "-/+" },
	oplus: { u: "⊕", a: "(+)" },
	otimes: { u: "⊗", a: "(x)" },
	circ: { u: "∘", a: "o" },
	bullet: { u: "•", a: "*" },
	cap: { u: "∩", a: "cap" },
	cup: { u: "∪", a: "cup" },
	wedge: { u: "∧", a: "and" },
	land: { u: "∧", a: "and" },
	vee: { u: "∨", a: "or" },
	lor: { u: "∨", a: "or" },
	setminus: { u: "∖", a: "\\" },
	// Arrows
	to: { u: "→", a: "->" },
	rightarrow: { u: "→", a: "->" },
	leftarrow: { u: "←", a: "<-" },
	leftrightarrow: { u: "↔", a: "<->" },
	Rightarrow: { u: "⇒", a: "=>" },
	Leftarrow: { u: "⇐", a: "<=" },
	Leftrightarrow: { u: "⇔", a: "<=>" },
	mapsto: { u: "↦", a: "|->" },
	implies: { u: "⟹", a: "=>" },
	iff: { u: "⟺", a: "<=>" },
	// Set / logic / misc
	in: { u: "∈", a: "in" },
	notin: { u: "∉", a: "not in" },
	ni: { u: "∋", a: "ni" },
	forall: { u: "∀", a: "for all" },
	exists: { u: "∃", a: "exists" },
	nexists: { u: "∄", a: "not exists" },
	neg: { u: "¬", a: "not" },
	emptyset: { u: "∅", a: "{}" },
	varnothing: { u: "∅", a: "{}" },
	infty: { u: "∞", a: "inf" },
	partial: { u: "∂", a: "d" },
	nabla: { u: "∇", a: "nabla" },
	angle: { u: "∠", a: "angle" },
	perp: { u: "⊥", a: "perp" },
	parallel: { u: "∥", a: "||" },
	mid: { u: "∣", a: "|" },
	cdots: { u: "⋯", a: "..." },
	ldots: { u: "…", a: "..." },
	dots: { u: "…", a: "..." },
	vdots: { u: "⋮", a: ":" },
	ddots: { u: "⋱", a: "..." },
	prime: { u: "′", a: "'" },
	hbar: { u: "ℏ", a: "hbar" },
	ell: { u: "ℓ", a: "l" },
	Re: { u: "ℜ", a: "Re" },
	Im: { u: "ℑ", a: "Im" },
	aleph: { u: "ℵ", a: "aleph" },
	degree: { u: "°", a: "deg" },
	// Named operators rendered upright
	sin: { u: "sin", a: "sin" },
	cos: { u: "cos", a: "cos" },
	tan: { u: "tan", a: "tan" },
	cot: { u: "cot", a: "cot" },
	sec: { u: "sec", a: "sec" },
	csc: { u: "csc", a: "csc" },
	arcsin: { u: "arcsin", a: "arcsin" },
	arccos: { u: "arccos", a: "arccos" },
	arctan: { u: "arctan", a: "arctan" },
	sinh: { u: "sinh", a: "sinh" },
	cosh: { u: "cosh", a: "cosh" },
	tanh: { u: "tanh", a: "tanh" },
	log: { u: "log", a: "log" },
	ln: { u: "ln", a: "ln" },
	exp: { u: "exp", a: "exp" },
	det: { u: "det", a: "det" },
	dim: { u: "dim", a: "dim" },
	gcd: { u: "gcd", a: "gcd" },
	max: { u: "max", a: "max" },
	min: { u: "min", a: "min" },
	arg: { u: "arg", a: "arg" },
	deg: { u: "deg", a: "deg" },
};

/**
 * Big operators that grow and take under/over limits in display mode.
 * `lim` is included as a 3-char operator whose limit sits underneath.
 */
export const BIG_OPERATORS: Record<string, Glyph> = {
	sum: { u: "∑", a: "Sum" },
	prod: { u: "∏", a: "Prod" },
	coprod: { u: "∐", a: "Coprod" },
	int: { u: "∫", a: "Int" },
	oint: { u: "∮", a: "Oint" },
	iint: { u: "∬", a: "Int2" },
	iiint: { u: "∭", a: "Int3" },
	bigcup: { u: "⋃", a: "Union" },
	bigcap: { u: "⋂", a: "Inter" },
	bigoplus: { u: "⨁", a: "(+)" },
	bigotimes: { u: "⨂", a: "(x)" },
	lim: { u: "lim", a: "lim" },
	limsup: { u: "limsup", a: "limsup" },
	liminf: { u: "liminf", a: "liminf" },
	sup: { u: "sup", a: "sup" },
	inf: { u: "inf", a: "inf" },
};

/** Blackboard-bold (\mathbb) for the common letters that exist in Unicode. */
export const MATHBB: Record<string, string> = {
	A: "𝔸",
	B: "𝔹",
	C: "ℂ",
	D: "𝔻",
	E: "𝔼",
	F: "𝔽",
	G: "𝔾",
	H: "ℍ",
	I: "𝕀",
	J: "𝕁",
	K: "𝕂",
	L: "𝕃",
	M: "𝕄",
	N: "ℕ",
	O: "𝕆",
	P: "ℙ",
	Q: "ℚ",
	R: "ℝ",
	S: "𝕊",
	T: "𝕋",
	U: "𝕌",
	V: "𝕍",
	W: "𝕎",
	X: "𝕏",
	Y: "𝕐",
	Z: "ℤ",
};

/** Single-character Unicode superscripts (the height-1 fast path for `^`). */
export const SUPERSCRIPTS: Record<string, string> = {
	"0": "⁰",
	"1": "¹",
	"2": "²",
	"3": "³",
	"4": "⁴",
	"5": "⁵",
	"6": "⁶",
	"7": "⁷",
	"8": "⁸",
	"9": "⁹",
	"+": "⁺",
	"-": "⁻",
	"=": "⁼",
	"(": "⁽",
	")": "⁾",
	".": "·",
	a: "ᵃ",
	b: "ᵇ",
	c: "ᶜ",
	d: "ᵈ",
	e: "ᵉ",
	f: "ᶠ",
	g: "ᵍ",
	h: "ʰ",
	i: "ⁱ",
	j: "ʲ",
	k: "ᵏ",
	l: "ˡ",
	m: "ᵐ",
	n: "ⁿ",
	o: "ᵒ",
	p: "ᵖ",
	r: "ʳ",
	s: "ˢ",
	t: "ᵗ",
	u: "ᵘ",
	v: "ᵛ",
	w: "ʷ",
	x: "ˣ",
	y: "ʸ",
	z: "ᶻ",
};

/** Single-character Unicode subscripts (the height-1 fast path for `_`). */
export const SUBSCRIPTS: Record<string, string> = {
	"0": "₀",
	"1": "₁",
	"2": "₂",
	"3": "₃",
	"4": "₄",
	"5": "₅",
	"6": "₆",
	"7": "₇",
	"8": "₈",
	"9": "₉",
	"+": "₊",
	"-": "₋",
	"=": "₌",
	"(": "₍",
	")": "₎",
	a: "ₐ",
	e: "ₑ",
	h: "ₕ",
	i: "ᵢ",
	j: "ⱼ",
	k: "ₖ",
	l: "ₗ",
	m: "ₘ",
	n: "ₙ",
	o: "ₒ",
	p: "ₚ",
	r: "ᵣ",
	s: "ₛ",
	t: "ₜ",
	u: "ᵤ",
	v: "ᵥ",
	x: "ₓ",
};

/**
 * Scalable delimiter pieces for `\left … \right`, keyed by the delimiter glyph.
 * `top`/`bot`/`ext` build a multi-row bracket; `mid` is the single-row glyph.
 */
export interface DelimPieces {
	mid: string;
	top: string;
	ext: string;
	bot: string;
}

export const DELIMS_UNICODE: Record<string, DelimPieces> = {
	"(": { mid: "(", top: "⎛", ext: "⎜", bot: "⎝" },
	")": { mid: ")", top: "⎞", ext: "⎟", bot: "⎠" },
	"[": { mid: "[", top: "⎡", ext: "⎢", bot: "⎣" },
	"]": { mid: "]", top: "⎤", ext: "⎥", bot: "⎦" },
	"{": { mid: "{", top: "⎧", ext: "⎪", bot: "⎩" },
	"}": { mid: "}", top: "⎫", ext: "⎪", bot: "⎭" },
	"|": { mid: "|", top: "│", ext: "│", bot: "│" },
	"/": { mid: "/", top: "╱", ext: "╱", bot: "╱" },
	"\\": { mid: "\\", top: "╲", ext: "╲", bot: "╲" },
	"⌊": { mid: "⌊", top: "⎡", ext: "⎢", bot: "⌊" },
	"⌋": { mid: "⌋", top: "⎤", ext: "⎥", bot: "⌋" },
	"⌈": { mid: "⌈", top: "⌈", ext: "⎢", bot: "⎣" },
	"⌉": { mid: "⌉", top: "⌉", ext: "⎥", bot: "⎦" },
	angle: { mid: "⟨", top: "╱", ext: "│", bot: "╲" },
	rangle: { mid: "⟩", top: "╲", ext: "│", bot: "╱" },
};

export const DELIMS_ASCII: Record<string, DelimPieces> = {
	"(": { mid: "(", top: "/", ext: "|", bot: "\\" },
	")": { mid: ")", top: "\\", ext: "|", bot: "/" },
	"[": { mid: "[", top: "[", ext: "|", bot: "[" },
	"]": { mid: "]", top: "]", ext: "|", bot: "]" },
	"{": { mid: "{", top: "/", ext: "|", bot: "\\" },
	"}": { mid: "}", top: "\\", ext: "|", bot: "/" },
	"|": { mid: "|", top: "|", ext: "|", bot: "|" },
	"/": { mid: "/", top: "/", ext: "/", bot: "/" },
	"\\": { mid: "\\", top: "\\", ext: "\\", bot: "\\" },
};

/** Map of `\left`/`\right` delimiter tokens to a glyph key in the DELIMS maps. */
export const DELIM_ALIASES: Record<string, string> = {
	"(": "(",
	")": ")",
	"[": "[",
	"]": "]",
	"|": "|",
	"/": "/",
	"\\": "\\",
	"\\{": "{",
	"\\}": "}",
	lfloor: "⌊",
	rfloor: "⌋",
	lceil: "⌈",
	rceil: "⌉",
	langle: "angle",
	rangle: "rangle",
	vert: "|",
	lvert: "|",
	rvert: "|",
	".": "",
};
